-- DDL: CREATE TABLES & CONSTRAINTS
CREATE TABLE CUSTOMER (
    CUSTOMER_ID VARCHAR(10),
    CUSTOMER_NAME VARCHAR(50) NOT NULL,
    CITY VARCHAR(30),
    MEMBERSHIP_LEVEL VARCHAR(20),
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE ORDERS (
    ORDER_ID VARCHAR(10),
    CUSTOMER_ID VARCHAR(10),
    ORDER_DATE DATE,
    SHIPPING_CITY VARCHAR(30),
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID VARCHAR(10),
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(30),
    UNIT_PRICE NUMERIC(8, 2),
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE ORDER_ITEM (
    ORDER_ID VARCHAR(10),
    PRODUCT_ID VARCHAR(10),
    QUANTITY NUMERIC(4, 0),
    DISCOUNT NUMERIC(4, 2),
    PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);

CREATE TABLE VENDOR (
    VENDOR_ID VARCHAR(10),
    VENDOR_NAME VARCHAR(50) NOT NULL,
    CITY VARCHAR(30),
    PRIMARY KEY (VENDOR_ID)
);

CREATE TABLE SUPPLIES (
    VENDOR_ID VARCHAR(10),
    PRODUCT_ID VARCHAR(10),
    STOCK_QUANTITY NUMERIC(6, 0),
    PRIMARY KEY (VENDOR_ID, PRODUCT_ID),
    FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR (VENDOR_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);

-- DML: INSERT SAMPLE DATA
INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CITY, MEMBERSHIP_LEVEL) VALUES
    ('C101', 'Alice Johnson', 'Seattle', 'Gold'),
    ('C102', 'Bob Smith', 'San Francisco', 'Silver'),
    ('C103', 'Charlie Davis', 'Chicago', 'Bronze'),
    ('C104', 'Diana Prince', 'Seattle', 'Gold'),
    ('C105', 'Evan Wright', 'New York', 'Bronze');

INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, SHIPPING_CITY) VALUES
    ('O500', 'C101', '2026-03-01', 'Seattle'),
    ('O501', 'C102', '2026-03-02', 'San Francisco'),
    ('O502', 'C101', '2026-03-05', 'Seattle'),
    ('O503', 'C103', '2026-03-07', 'Chicago'),
    ('O504', 'C104', '2026-03-10', 'San Francisco');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, CATEGORY, UNIT_PRICE) VALUES
    ('P001', 'SuperWidget', 'Electronics', 599.99),
    ('P002', 'UltraBook Pro', 'Electronics', 1200.00),
    ('P003', 'Database Concepts', 'Books', 75.50),
    ('P004', 'Ergonomic Desk Chair', 'Furniture', 250.00),
    ('P005', 'Wireless Headphones', 'Electronics', 150.00);

INSERT INTO ORDER_ITEM (ORDER_ID, PRODUCT_ID, QUANTITY, DISCOUNT) VALUES
    ('O500', 'P001', 1, 0.05),
    ('O500', 'P003', 2, 0.00),
    ('O501', 'P002', 1, 0.10),
    ('O502', 'P004', 1, 0.00),
    ('O503', 'P003', 1, 0.00),
    ('O504', 'P001', 2, 0.15),
    ('O504', 'P005', 1, 0.00);

INSERT INTO VENDOR (VENDOR_ID, VENDOR_NAME, CITY) VALUES
    ('V101', 'TechCorp', 'Seattle'),
    ('V102', 'GlobalSupply', 'San Francisco'),
    ('V103', 'BookCentral', 'Chicago'),
    ('V104', 'OfficeDepot Direct', 'New York');

INSERT INTO SUPPLIES (VENDOR_ID, PRODUCT_ID, STOCK_QUANTITY) VALUES
    ('V101', 'P001', 500),
    ('V101', 'P002', 150),
    ('V101', 'P005', 300),
    ('V102', 'P001', 200),
    ('V102', 'P004', 80),
    ('V103', 'P003', 1200),
    ('V104', 'P004', 150);